services:
  - type: web
    name: recipe-llm-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: CLIENT_TOKEN
        generateValue: true
      - key: GEMINI_MODEL
        value: gemini-1.5-flash
      - key: CORS_ORIGINS
        value: "*"
